version: '3.7'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: algamoneydb
    ports:
      - "3306:3306"
    networks:
      - algamoney-api-network
  app-server:
    image: algamoney-api
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    # working_dir: /app
    environment: 
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/algamoneydb?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    ports: 
      - "8080:8080"
    depends_on: 
      - db
    networks: 
      - algamoney-api-network
networks:
  algamoney-api-network:
    driver: bridge
