version: '3.4'
services:
    db:
        image: mysql:5.7.22
        command: mysqld --default_authentication_plugin=mysql_native_password
        restart: always
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: algamoneydb
        ports:
            - "3306:3306"
        networks:
            - algamoney-api-network

networks:
    algamoney-api-network:
        driver: bridge
