version: '3.4'
services:
  db:
    images: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
        restart: always
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: wordpress
        ports:
            - "3308:3306"
        networks:
            - algamoney-network
networks:
    algamoney-network:
        driver: bridge