version: '3.7'
services:
  db:
    image: mysql:5.7.22
    restart: always
    build: 
      context: mysql
      dockerfile: Dockerfile
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: algamoneydb
    ports:
      - "3306:3306"
    networks: 
      - mysql-network

networks:
  mysql-network:
    driver: bridge